buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
    }
}

// allprojects {
//     layout.buildDirectory = file("/tmp/gradle-builds/MarkaLista/${project.name}")
// }

task clean(type: Delete) {
    delete layout.buildDirectory
}
