android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
systemProp.COPYFILE_DISABLE=true
org.gradle.java.home=/Users/marekzele/Library/Java/JavaVirtualMachines/jbr-21.0.11/Contents/Home
org.gradle.file.watch.enabled=false
org.gradle.vfs.watch.enabled=false
android.enableResourceCompression=false
