plugins {
    id 'com.android.application'
}

android {
    namespace "com.marek.markalista"
    compileSdk 34

    defaultConfig {
        applicationId "com.marek.markalista"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "0.1-coming-soon"
    }



    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    androidResources {
        ignoreAssetsPattern '!:._*'
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
}
